set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
"autocomplete
Bundle 'neocomplcache'

Bundle 'JavaScript-syntax'
Bundle 'jQuery'
Bundle 'othree/html5.vim'
Bundle 'php.vim-html-enhanced'
Bundle 'mattn/emmet-vim'  
Bundle "snipmate-snippets"

Bundle 'altercation/vim-colors-solarized' 

let g:neocomplcache_enable_at_startup = 1 

let &termencoding=&encoding
set fileencodings=utf-8,gbk

set number
set autoread
set ruler


" Tab related  
set shiftwidth=4  
set tabstop=4  
set softtabstop=4  
set expandtab               " Use spaces instead of tabs 


if has("win32")
	colorscheme desert
	set guifont=Yahei\ Mono:h10
else
	set guifont=Monaco:h12
	set t_Co=256                " Explicitly tell vim that the terminal supports 256 colors, need before setting the colorscheme  
	let g:solarized_termcolors=256  
	colorscheme solarized  
	set background=dark  
endif

if has('gui_running')
    set background=light
else
    set background=dark
endif

":autocmd FileType php noremap <C-M> :w!<CR>:!/usr/bin/php %<CR>
:map <F5> :w!<CR>:!/usr/bin/php %<CR>
