language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

script: phpunit --configuration phpunit.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"